sudo: required

language: node_js

services:
  - docker

node_js:
  - "11"

notifications:
  email:
    - starinje@gmail.com
  slack: health-scord:wnICySJUJoRcO0pqA5AtxYOB

before_script:
  - docker build -t score-calculation-service .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
